name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: npm
          registry-url: https://registry.npmjs.org

      - run: npm ci
      - run: npx eslint src/
      - run: npx tsc --noEmit
      - run: npx vitest run
      - run: npx tsc
      - run: npm publish --provenance --access public
